### PR TITLE
Implement unsafe overclocking safety overrides

### PR DESCRIPTION
**Pull request by rukai**
I am porting a C firmware that slightly overclocks the following values on an stm32f439.
* SYSCLK 192MHz (max 180MHz)
* APB1/PCLK1/PPRE1_register 48Mhz (max 45MHz)
* APB2/PCLK2/PPRE2_register 96Mhz (max 90MHz)

I need to maintain these clock speeds in the rust port, so my usage will look like this:

```rust
    let clocks = unsafe {
        rcc.cfgr
            .use_hse(4.mhz())
            .sysclk(192.mhz())
            .hclk(192.mhz())
            .pclk1(48.mhz())
            .pclk2(96.mhz())
            .sysclk_allow_overclock()
            .pclk1_allow_overclock()
            .pclk2_allow_overclock()
            .freeze()
        };
```

Would love to hear suggestions for better naming of the builder method names.

### CODE REVIEW

**Comment by TeXitoi** [comment]
I'll do a `unsafe pub freeze_unchecked(self)`

**Comment by rukai** [comment]
Sure, sounds like you are implementing it yourself, so should I close this PR?

**Comment by TeXitoi** [comment]
That's just a naming proposition.

**Comment by rukai** [comment]
A single `freeze_unchecked` method instead of the 3 `*_allow_overclock` methods would be fine by me.

Would it also suppress this assert? `assert!(vco_in >= 1_000_000 && vco_in <= 2_000_000);`
I have no idea if that is a good idea or not, the C code I am porting doesnt break this assert.

I'll wait for a maintainer to say which api they prefer before I rewrite it.

**Comment by therealprof** [comment]
`freeze_unchecked` sounds like a better idea to me, too.

**Comment by rukai** [comment]
done!

**Review by TeXitoi — APPROVED** [review]

**Pull request merged**
