### PR TITLE
offer `clear_idle_interrupt` from `serial::Rx` in DMA `Transfer`

### PR DESCRIPTION
**Pull request by rursprung**
please see the individual commit messages for further details.
i've tested this on an STM32F401.

this solves #550.

### CODE REVIEW

**Comment by burrbull** [comment]
looks like SerialISR is just RxISR + TxISR.
In this case it is better to to remove SerialISR and implement RxISR and TxISR for Serial

**Comment by rursprung** [comment]
> looks like SerialISR is just RxISR + TxISR. In this case it is better to to remove SerialISR and implement RxISR and TxISR for Serial

good catch! i've adapted it accordingly

**Comment by burrbull** [comment]
and reexport in prelude

**Comment by rursprung** [comment]
> and reexport in prelude

done

**Review by burrbull — APPROVED** [review]

**Pull request merged**
