### PR TITLE
Update to embedded-hal 1.0.0-alpha.8

### PR DESCRIPTION
**Pull request by quentinmit**

### CODE REVIEW

**Comment by burrbull** [comment]
Looks good to me. Do you have working example with 1.0 spi to add to examples? @eldruin maybe?

**Comment by burrbull** [comment]
need CHANGELOG.md update

**Comment by quentinmit** [comment]
> need CHANGELOG.md update

Done.

**Comment by eldruin** [comment]
I have not converted any driver yet, I will try to do so in the next few days.

**Comment by eldruin** [comment]
Ok I have converted the [AD983x SPI synthesizer driver](https://github.com/eldruin/ad983x-rs) and [wrote an example for this HAL](https://github.com/eldruin/stm32f4xx-hal/blob/add-spi-driver-example-e-h-1.0.0-alpha.8/examples/spi-ad9833-synth.rs) using this branch.
It was straight forward to adapt but I have not tested it in hardware.

**Review by burrbull — APPROVED** [review]

**Pull request merged**
