### PR TITLE
Bump stm32f4 to 0.10.0

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by TeXitoi** [comment]
The last step before a new publication on crates.io? :innocent:

**Comment by therealprof** [comment]
Currently looking at other low hanging fruit, but yes, planning to do it soon.

**Comment by therealprof** [comment]
Since you seem quite active at reviewing PRs and helping out so much, would you like to join the maintainer team?

**Comment by TeXitoi** [comment]
with pleasure

**Pull request merged**
