### PR TITLE
Add bidirectional mode for spi

### PR DESCRIPTION
**Pull request by no111u3**
Add bidirectional mode for spi. As previous pr #210 this pr provide bidi mode for spi but more confidence and feature full.

### CODE REVIEW

**Comment by burrbull** [comment]
About error flags https://github.com/stm32-rs/stm32f4xx-hal/pull/223

**Comment by burrbull** [comment]
It would be nice to have example describing how to use different modes.

**Comment by no111u3** [comment]
> About error flags #223

Fixed.

**Comment by no111u3** [comment]
> It would be nice to have example describing how to use different modes.

Will be added later

**Review by burrbull — APPROVED** [review]

**Comment by no111u3** [comment]
> It would be nice to have example describing how to use different modes.
Add simple example witch use SPI BiDi mode for transfer data.

**Review by burrbull — APPROVED** [review]

**Pull request merged**
