### PR TITLE
SysMonoTimerExt

### PR DESCRIPTION
**Pull request by burrbull**
r? @therealprof 

should I enable `rtic` feature by-default / remove it ?

### CODE REVIEW

**Comment by therealprof** [comment]
> should I enable `rtic` feature by-default / remove it ?

Not sure. Is it obvious from the documentation that some features are only available for `rtic`?

**Comment by burrbull** [comment]
> > should I enable `rtic` feature by-default / remove it ?
> 
> Not sure. Is it obvious from the documentation that some features are only available for `rtic`?

probably not

**Comment by therealprof** [comment]
Hm, then maybe not. I'll leave it up to you to decide.

**Comment by burrbull** [comment]
Ok. For now I won't change it.

**Review by therealprof — APPROVED** [review]
LGTM

bors r+

**Pull request merged**
