### PR TITLE
add VS Code & JetBrains IDEA (RustRover, CLion, etc.) to `.gitignore`

### PR DESCRIPTION
**Pull request by rursprung**

### CODE REVIEW

**Comment by rursprung** [comment]
note that i intentionally didn't add this to the changelog, it's irrelevant for consumers of the crate. it's just helpful when working with the repository with an IDE to avoid constantly seeing an untracked file being reported

**Comment by burrbull** [comment]
In this logic `.lapce` should also be there.

**Comment by rursprung** [comment]
> In this logic `.lapce` should also be there.

done. i wasn't aware of this IDE

**Comment by burrbull** [comment]
`no changelog` label does not work for this repo. Don't know why. Need to fix.

**Pull request merged**
