### PR TITLE
Implement Cancel trait for Timer<SYST>

### PR DESCRIPTION
**Pull request by MarcoIeni**
This partially solves #106, because only I implemented `cancel()` only for `Timer<SYST>`. I would like to implement `Timer<$TIM>` once this is approved.

The error `Disabled` is returned because the timer [documentation](https://docs.rs/crate/embedded-hal/0.2.3/source/src/timer.rs) says:

> An error will be returned if the countdown has already been canceled or was never started.

## example

I added an example that shows how `cancel()` works, but I have a question: why the example doesn't work if I remove `use embedded_hal::timer::Cancel;`? For example the `wait()` function works even if CountDown is not imported explicitly.

### CODE REVIEW

**Comment by MarcoIeni** [comment]
The `disable_counter()` is also used [here](https://docs.rs/stm32f1xx-hal/0.5.3/src/stm32f1xx_hal/timer.rs.html#248)

**Comment by therealprof** [comment]
Thanks for the PR.

> I added an example that shows how cancel() works, but I have a question: why the example doesn't work if I remove use embedded_hal::timer::Cancel;? For example the wait() function works even if CountDown is not imported explicitly.

Maybe `embedded_hal::timer::Cancel` is not in the prelude of `embedded-hal`? We can always add it to this crates prelude so at least that should work nicely.

Other than that looks good to me but I need to take a closer look.

**Comment by therealprof** [comment]
@MarcoIeni Sorry for taking so long until I got it. Looks good to me but would you please add a CHANGELOG entry for that?

**Comment by MarcoIeni** [comment]
on my machine formatting looks good, I have rust 1.43 and `cargo fmt --all -- --check` succeeds.
There is an error in the CI or am I missing something?

**Comment by therealprof** [comment]
Not sure but this rustfmt decided that the order should be different. Looks good though.

**Pull request merged**
