### PR TITLE
Add change log check

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by Disasm** [comment]
/* Missing change log entry is intended at the moment :) */

**Comment by Disasm** [comment]
Well, this changelog check apparently failed to check:
```
(node:2468) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/Zomzog/changelog-checker/v1.1.0/dist/index.js:7752:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Disasm** [comment]
@therealprof https://github.com/actions/first-interaction/issues/10#issuecomment-545576314
Could you try making such PR by yourself?

**Comment by Disasm** [comment]
Probably this will not work at all, if it fails to work for PRs originated from forks (like it usually happens). Sigh.

**Comment by Disasm** [comment]
Closing the PR as this problem requires a different solution.

**Comment by Disasm** [comment]
See also: https://github.com/probe-rs/probe-rs/pull/428#issuecomment-731154770

**Comment by thalesfragoso** [comment]
Any news on this ? Why the check doesn't appear on the last commit ?

**Comment by Disasm** [comment]
@thalesfragoso @therealprof This PR can be merged. I tested it on a separate repo and this approach works.
When you add the changelog rule with a PR from the external repo, it doesn't work instantly (like in this PR): https://github.com/archlinux-riscv/ci-sandbox/pull/1
but after the merge it runs for all the following PRs: https://github.com/archlinux-riscv/ci-sandbox/pull/2, https://github.com/archlinux-riscv/ci-sandbox/pull/3
Note that `no changelog` label doesn't work for some reason, even if I re-run the CI check.

**Review by therealprof — APPROVED** [review]
Thanks, @Disasm . Let's see how it goes.

bors r+

**Pull request merged**
