### PR TITLE
Add CRC peripheral

### PR DESCRIPTION
**Pull request by jamesmunns**

### CODE REVIEW

**Comment by Disasm** [comment]
I'd prefer to call functions `init` (performs reset in this case) and `update` (feeds without resetting) as they are commonly used in other libraries.

**Comment by therealprof** [comment]
I tend to agree with @Disasm here that `feed` is a bit boutique. 😅

**Comment by jamesmunns** [comment]
Addressed comments!

**Review by therealprof — CHANGES_REQUESTED** [review]
Missing CHANGELOG entry, other than that looks very nice to me.

**Review by therealprof — APPROVED** [review]
Thanks a lot!

bors r+

**Pull request merged**
