### PR TITLE
RCC: Add option to bypass HSE oscillator

### PR DESCRIPTION
**Pull request by samcrow**
This change adds an option to set the HSEBYP bit of RCC_CR, which disables the built-in oscillator for the HSE clock. Instead, the microcontroller can use a clock signal from an external oscillator or other source.

I have tested this mode on a 32F412GDISCOVERY board.

### CODE REVIEW

**Review by matoushybl — DISMISSED** [review]
LGTM, thanks for the PR!

**Comment by thalesfragoso** [comment]
Thank you, could you resolve the conflicts ?

**Comment by samcrow** [comment]
OK, it looks like I've resolved the conflict in the changelog.

**Review by thalesfragoso — APPROVED** [review]
Thanks again!

bors r+

**Pull request merged**
