### PR TITLE
Stream x no generic

### PR DESCRIPTION
**Pull request by YruamaLairba**
Just to illustrate a discussion about StreamX

### CODE REVIEW

**Comment by YruamaLairba** [comment]
what ? i have commit duplication ???

**Comment by burrbull** [comment]
I still don't see explanation why you need this except now you can pass incorrect values in safe API.

**Comment by YruamaLairba** [comment]
> I still don't see explanation why you need this except now you can pass incorrect values in safe API.

I don't need this, i just don't understand why you need generic here. Can you tell me where in the API and how  it enable incorrect value ?

**Comment by burrbull** [comment]
> I don't need this, i just don't understand why you need generic here. Can you tell me where in the API and how it enable incorrect value ?

Your code don't do anything wrong.
But as `Stream` trait is public (should it be?), anyone can call `set_channel` with any `DmaChannel`. It is not my API, so I know not much more than you.

**Comment by YruamaLairba** [comment]
> anyone can call `set_channel` with any `DmaChannel`

But this doesn't enable incorrect value . With `fn set_channel<const C: u8>(&mut self)`, it's already possible to give any Channel number  between 0 and 7 without restriction. I Also read again the datasheet, i realized there is'nt really invalid channel values, There is just stupid values depending the situation

**Comment by burrbull** [comment]
> With `fn set_channel<const C: u8>(&mut self)`, it's already possible to give any Channel number between 0 and 7 without restriction.

You are right. This is hole in design.

**Comment by burrbull** [comment]
F413 has channels 8 and 9 on DMA2

**Comment by YruamaLairba** [comment]
@burrbull i just checked datasheet, there is actually 16 Channel for stm32f413. The higher channels just don't have peripheral connected to them

**Comment by burrbull** [comment]
изображение

8 and 9 are used

**Pull request closed without merging**
