### PR TITLE
Remove unsafe code from the ADC DMA example.

### PR DESCRIPTION
**Pull request by matoushybl**

### CODE REVIEW

**Review by thalesfragoso — CHANGES_REQUESTED** [review]
Thanks for the PR, but one thing, the DMA config enables double buffering but you're only providing one buffer to `Transfer::init`, this code will panic. If you want to remove `next_transfer_with` you will need 3 buffers for double buffering.

**Comment by matoushybl** [comment]
I disabled double buffering in the DMA config. Is it ok now?
Thanks for the comment, I've missed it.

**Comment by thalesfragoso** [comment]
Yes, it should be okay now, have you tried it on hardware ?

**Comment by matoushybl** [comment]
I've tried running it out of the HAL project in another with defmt and it worked, but I failed to make it run as an example in the project.
My gdb skills are terrible so I believe that that may have been a problem, or something with the project config.

**Comment by thalesfragoso** [comment]
Weird, but I don't see any problem with the code, so...

**Review by thalesfragoso — APPROVED** [review]
Thanks again!

bors r+

**Pull request merged**
