### PR TITLE
Example dead time2

### PR DESCRIPTION
**Pull request by janschiefer**
Advanced PWM dead time insertion example.

### CODE REVIEW

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
`cargo fmt` and modify https://github.com/stm32-rs/stm32f4xx-hal/blob/master/CHANGELOG.md

**Comment by janschiefer** [comment]
Done.

**Comment by burrbull** [comment]
Please, don't use "merge" to update pull request. Only "rebase".

**Review by burrbull — APPROVED** [review]

**Pull request merged**
