### PR TITLE
adding spi slave

### PR DESCRIPTION
**Pull request by Arnaud078**
as mentionned in issue https://github.com/stm32-rs/stm32f4xx-hal/issues/483

### CODE REVIEW

**Comment by Arnaud078** [comment]
I tested that roundtripping between all the modes is fine with :
let spi3 = Spi::new_slave(spi, (sck, miso, mosi), mode, 8_000_000.Hz(), &clocks);
        let spi3 = spi3.to_master_operation();
        let spi3 = spi3.to_bidi_transfer_mode();
        let spi3 = spi3.to_slave_operation();
        let spi3 = spi3.to_normal_transfer_mode();

Slave mode is able to transmit.

I can't test that nothing was broken in bidi or master mode though.

**Comment by burrbull** [comment]
Could you add any tested example?

**Comment by Arnaud078** [comment]
added tested example of spi slave with dma in rtic

**Comment by burrbull** [comment]
Add example to Cargo.toml with `rtic` feature.

What about `embedded-hal` traits? Are they usefull for master mode only?

**Comment by burrbull** [comment]
rustfmt

**Comment by Arnaud078** [comment]
Added example to Cargo.toml. I am not sure it will solve all the build errors though, I am using undeclared crates :/

I checked embedded-hal, but I don't see any reference to slave or master mode. I don't think I can reference other traits than what was already referenced. I think we can add the 2 new type structs there (Master & Slave), as it is now duplicated in stm32f1xx and stm32f4xx.

**Review by burrbull — APPROVED** [review]

**Comment by Arnaud078** [comment]
Great ! Thank you for your time.

**Pull request merged**
