### PR TITLE
Use CamelCase for gpio::Edge enum variants

### PR DESCRIPTION
**Pull request by Piroro-hs**
ref: [h7xx](https://github.com/stm32-rs/stm32h7xx-hal/pull/179), [l4xx](https://github.com/stm32-rs/stm32l4xx-hal/pull/187), [f1xx](https://github.com/stm32-rs/stm32f1xx-hal/pull/303), [f7xx](https://github.com/stm32-rs/stm32f7xx-hal/pull/111)

### CODE REVIEW

**Comment by therealprof** [comment]
Thanks for your PR. I don't think we should apply it though since it will break all applications out there using this functionality without good reason.

**Comment by Piroro-hs** [comment]
I thought that it can be fixed for now as this and other stm32 HALs does not reached to v1.0.0.

**Comment by therealprof** [comment]
> Thanks for fast reply!
> I thought that it can be fixed for now as this and other stm32 HALs does not reached to v1.0.0.

Well, yes and no. 😅 1.0 is just a label and the question is whether those crates will ever reach "1.0" since every change to the svd files or `svd2rust` have to be considered a breaking change and would have to result in an inflationary major version bumping... I'm not opposed to necessary breaking changes (to fix bugs or usability shortcomings) but this particular change seems to lack a good motive.

**Comment by burrbull** [comment]
Rebase, please.

**Pull request closed without merging**
