### PR TITLE
Bumped stm32f4 dependency to 0.12

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
@thalesfragoso Seems some DMA bits have changed, at least they failed to compile in my local tests:

```
error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
   --> src/dma/mod.rs:353:56
    |
353 |                       dma.st[Self::NUMBER].par.write(|w| w.pa().bits(value));
    |                                                          ^^^^^^^^^^^^^^^^^^ call to unsafe function
...
600 | / dma_stream!(
601 | |     (Stream0, 0, lifcr, ctcif0, chtif0, cteif0, cdmeif0, cfeif0, lisr, tcif0, htif0),
602 | |     (Stream1, 1, lifcr, ctcif1, chtif1, cteif1, cdmeif1, cfeif1, lisr, tcif1, htif1),
603 | |     (Stream2, 2, lifcr, ctcif2, chtif2, cteif2, cdmeif2, cfeif2, lisr, tcif2, htif2),
...   |
608 | |     (Stream7, 7, hifcr, ctcif7, chtif7, cteif7, cdmeif7, cfeif7, hisr, tcif7, htif7),
609 | | );
    | |__- in this macro invocation
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by thalesfragoso** [comment]
Hmm, it kinda makes sense, although all values are theoretical valid for that register, it might still be problematic, so `unsafe` seems correct. It's a simple update.

**Comment by therealprof** [comment]
@thalesfragoso So you're saying we should just slap an unsafe on all of those and be fine?

**Comment by thalesfragoso** [comment]
> So you're saying we should just slap an unsafe on all of those and be fine?

With respect to the addresses' registers for the DMA, yes.

**Comment by therealprof** [comment]
Obsoleted by #288

**Pull request closed without merging**
