### PR TITLE
Add support for SCSD cards with SDIO

### PR DESCRIPTION
**Pull request by glbsalazar**
Add support for SCSD cards in the SDIO interface
Added the timeout since setting the bus width and frequency was timing out because the card was not ready.

### CODE REVIEW

**Comment by jkristell** [comment]
Thanks for looking at this. What kind of card is this tested with? Do read and write work?

**Comment by glbsalazar** [comment]
It was tested with a generic unbranded 2GB micro sd card. 
I tested it by writting checking that the CID, CSD, OCR, RCA and SCR made sense and by writing a block and reading it out and checked that the values were correct.

**Comment by jkristell** [comment]
I'm gonna test this with my board just to make sure SDHC cards still works.

But I'm a bit confused, I thought that the `read/write_block` would had to be modified to handle byte addressed cards.

What is the CSD version on the card?

**Comment by glbsalazar** [comment]
It's a V2 card. I also tested it with a SDHC card (8GB) and it was also working, but I can retest everything latter tonight.

What changes were you thinking were needed?

**Comment by jkristell** [comment]
If it's a V2 card then it is block addressed and it explains why reading and writing works, right?

Hmm, maybe this shouldn't be classified as a SDSC card, perhaps we should look at at the csd version too, and then just classify this as a SDHC. There is probably somethings in the spec about this, or this card is just odd :)

**Comment by glbsalazar** [comment]
I might have done something strange, because the spec indeed states it is byte addressed for SDSC (and makes no consideration of version).
I will do some more tests, because looking at them now they did not cover all cases.
I'll try to retest it and update this later today. 
Thanks for the inputs :)

**Comment by jkristell** [comment]
I was a bit surprised a SDSC in microSD format even existed. So let's not rule out this is some strange card from a vendor doing something weird here :).

**Comment by glbsalazar** [comment]
@jkristell I added the proper handle for the SDSC cards, I previously missed some things in the tests.
Thanks for the input :)

**Comment by jkristell** [comment]
This looks like how I imagined the support for SDSC would look like. Thanks for looking into and fixing this!

**Comment by jkristell** [comment]
I don't have write access to the repo, so pinging @therealprof @thalesfragoso and asking them to merge this now.

**Comment by therealprof** [comment]
@jkristell If you're happy, let's get this merged. ;)

**Comment by jkristell** [comment]
I am! :) So let's merge it.

**Review by therealprof — APPROVED** [review]
bors r+

**Pull request merged**
