### PR TITLE
Addressing issue 501 with start_pwm

### PR DESCRIPTION
**Pull request by ganzalt**
I'm trying to use timer 2 of an STM32F411-Nucleo board and pin PA0 to generate PWM signals with varying duration and duty cycles. But I observed glitches in the generated signal because the ARPE bit in the timer's control register is cleared with calling the start_pwm method. Unfortunately, this method uses a register.write instead of register.modify to start PWM,

### CODE REVIEW

**Comment by burrbull** [comment]
update changelog, please

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
Forgot about this. Could you rebase, please?

**Comment by burrbull** [comment]
No. No. Please, no "merge" in PR. Rebase. Or make other PR.

**Comment by ganzalt** [comment]
Sorry, it starts to get too complicated for me to align the branches. Seems to be easiest to close the PR and setup a new fork and create a new PR.

**Pull request closed without merging**
