### PR TITLE
Move embedded-hal implementations to subdirs

### PR DESCRIPTION
**Pull request by burrbull**
Part of #388

### CODE REVIEW

**Review by therealprof — APPROVED** [review]
Oh wow, big chunk of work... 😅

LGTM, thanks.

bors r+

**Comment by burrbull** [comment]
What do you think about making release now?

**Comment by therealprof** [comment]
What about your open PRs? #372 and #396?

**Comment by burrbull** [comment]
> What about your open PRs? #372 and #396?

I've planned to wait for @gernoteger to reply a couple of days. Otherwise I'll rebase #396 myself.

**Pull request merged**
