### PR TITLE
use RTIC 1.0, fix warnings

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by therealprof — CHANGES_REQUESTED** [review]
I think moving to Edition 2021 is maybe a bit too early. I don't see the pressing need to limit the possible Rust compilers just yet. If we really want to go there now we should do another edition 2018 release first.

**Comment by burrbull** [comment]
> I think moving to Edition 2021 is maybe a bit too early. I don't see the pressing need to limit the possible Rust compilers just yet. If we really want to go there now we should do another edition 2018 release first.

Ok. Resonable. Reversed

**Review by therealprof — DISMISSED** [review]
LGTM, thanks.

**Comment by burrbull** [comment]
bors r=therealprof

**Comment by burrbull** [comment]
bors retry

**Comment by burrbull** [comment]
bors retry

**Comment by burrbull** [comment]
Four tries and each time 1 of tasks freezes.

**Comment by burrbull** [comment]
bors retry

**Comment by burrbull** [comment]
bors r=therealprof

**Review by therealprof — APPROVED** [review]
bors r+

**Comment by therealprof** [comment]
> Four tries and each time 1 of tasks freezes.

Seems GH is having weird issues...

**Pull request merged**
