### PR TITLE
DMA: Fix problems with DMASet and timer wrappers

### LINKED ISSUE #227: TIM DMA transfer support
Hi,
I'm trying to implement the Dshot protocol, similar to the one WS2812B uses.
This is the code where I already fail:
```rust
let dma1_streams = dma::StreamsTuple::new(device.DMA1);
let dma_transfer = dma::Transfer::init(
    dma1_streams.4,
    device.TIM3.ccr1,
    cortex_m::singleton!(: [u16; 18] = [0; 18]).unwrap(),
    None,
    dma::config::DmaConfig::default()
        .fifo_enable(true)
        .memory_increment(true),
);
```
Unfortunately it doesn't let me compile and returns an error message:
```
the trait bound `stm32f4::generic::Reg<u32, stm32f4xx_hal::stm32::tim3::_CCR>: stm32f4xx_hal::dma::traits::PeriAddress` is not satisfied
the trait `stm32f4xx_hal::dma::traits::PeriAddress` is not implemented for `stm32f4::generic::Reg<u32, stm32f4xx_hal::stm32::tim3::_CCR>`
```
I've seen in the source code that it requires the struct `CCR1<pac::TIM3>` to use `TIM3_CH1`, but where do I get it from?

### PR DESCRIPTION
**Pull request by thalesfragoso**
The initial idea of the DMASet trait was that people could __unsafely__ implement it themselves from outside of the HAL. Unfortunately, we missed the problem with the fact that tuples are considered a foreign type. This PR drops the tuple approach but still maintains the check that DMASet provides.

I also added a fix for #227.
Fixes #227 

This is also a possible solution to #226, but it takes a different approach, it still forces people (or the HAL) to make a new type if they want a "non-default" memory size (or address). This is more verbose than just dropping the associated type of `PeriAddress` in favor of a generic parameter, but, IMO, the verbosity can be an advantage here.

Marking as a draft because I still want to make sure this works as intended and that there isn't another corner case, I also would like the opinion of @albru123

### CODE REVIEW

**Comment by almusil** [comment]
Hello,
any plan when this might be finished? I am having hard time to have DMA for ADC that actually does not own the ADC so I can configure ADC through the hal.

**Comment by thalesfragoso** [comment]
> I am having hard time to have DMA for ADC that actually does not own the ADC so I can configure ADC through the hal.

I don't think this PR will solve this. For that you need an implementation on the HAL abstraction itself (and maybe some new/modified methods, etc), similar to what was done for the serial. Each HAL peripheral abstraction will need to support DMA by itself.

**Comment by almusil** [comment]
Of course it would be better to have direct integration with HAL Adc, but with this PR I am able to at least have workaround using something like this:
```
pub(crate) struct AdcAddress;

unsafe impl PeriAddress for AdcAddress {
    type MemSize = u16;

    fn address(&self) -> u32 {
        unsafe { &(*ADC1::ptr()).dr as *const _ as u32 }
    }
}

unsafe impl DMASet<Stream0<DMA2>, Channel0, PeripheralToMemory> for AdcAddress {}
```

**Comment by thalesfragoso** [comment]
I think this is ready for review, @albru123 have you had the chance to try this to see if it solves your issue ?

**Comment by thalesfragoso** [comment]
Rebased.

**Comment by albru123** [comment]
I'm checking it right now, but feel free to push this forward (I'm a bit busy so if something goes wrong I might not be able to respond in time).

**Review by therealprof — APPROVED** [review]
LGTM, Let's move this forward.

bors r+

**Pull request merged**
