### PR TITLE
Better documentation of rng and prelude

### PR DESCRIPTION
**Pull request by jounathaen**
This adds doc comments to the rng and prelude module as well as to the re-export of the svd2rust API.

The rng documentation might repeat some information, but as the generated documentation splits this to multiple pages, I find it is better that way. I also added small example code to the documentation. The examples in the repository are nice, but I personally would favor examples inside the docs.

It might be good, if somebody reads over the prelude part to check that I'm not completely off-track there.

### CODE REVIEW

**Comment by jounathaen** [comment]
Ok, apparently a changelog entry is missing. Is this necessary in this case?

**Comment by therealprof** [comment]
> Ok, apparently a changelog entry is missing. Is this necessary in this case?

Why not? Improved documentation is noteworthy.

**Comment by jounathaen** [comment]
Ok, from my side this is ready for review.
I hope this is acceptable and helps somebody. Thank you all for your work on this project!
:slightly_smiling_face:

**Comment by burrbull** [comment]
Rebase, please.

**Comment by jounathaen** [comment]
Rebased!

**Review by burrbull — APPROVED** [review]

**Pull request merged**
