### PR TITLE
const generic pins

### PR DESCRIPTION
**Pull request by burrbull**
requires Rust 1.51
Depends on #323

### CODE REVIEW

**Comment by therealprof** [comment]
CC #272

**Comment by therealprof** [comment]
Sweet! I need to try it out in personally but I do like that very much.

**Comment by burrbull** [comment]
I think we need better names for generic types. Now we have:
```rust
PX<MODE, P, N>,
PXn<MODE, P>, // downgrade
Pin<MODE> // downgrade2
```

**Review by therealprof — APPROVED** [review]
Excellent work! Thanks.

bors r+

**Pull request merged**
