### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by TeXitoi** [comment]
Travis failed on cache fetching. I purged the cache and relaunched the test.

Do I open an issue about the cache to talk about how to fix it?

**Comment by therealprof** [comment]
Huh? I did the same. 😅

I guess we'll just remove the cache, it's just so broken for Rust projects.

**Comment by therealprof** [comment]
And published. 🎉

**Comment by TeXitoi** [comment]
Thanks!

**Pull request merged**
